### ISSUE TITLE
actix: error[E0373]: closure may outlive borrowed value when using #[api_v2_operation]

### ISSUE THREAD

**Issue by strohel** [wafflespeanut/paperclip#216]
paperclip version: 90038bfd (current `master`, to be v0.5)

user code:
```rust
/// The `/city/v1/get` endpoint. HTTP request: [`CityQuery`], response: [`CityResponse`].
///
/// Get city of given ID localized to given language.
#[api_v2_operation]
pub(crate) async fn get(query: Query<CityQuery>, app: Data<AppState>) -> JsonResult<CityResponse> {
    let locations_es_repo = LocationsElasticRepository(app.get_ref());
    let es_city = locations_es_repo.get_city(query.id).await?;

    Ok(Json(es_city.into_resp(app.get_ref(), query.language).await?))
}
```

This seems to work fine with paperclip v0.4.1, but if I try to update to current master, I get the following lifetime error:
```
error[E0373]: closure may outlive the current function, but it borrows `app`, which is owned by the current function
  --> src/handlers/city.rs:47:1
   |
47 | #[api_v2_operation]
   | ^^^^^^^^^^^^^^^^^^^
   | |
   | may outlive borrowed value `app`
   | in this macro invocation
48 | pub(crate) async fn get(query: Query<CityQuery>, app: Data<AppState>) -> JsonResult<CityResponse> {
49 |     let locations_es_repo = LocationsElasticRepository(app.get_ref());
   |                                                        --- `app` is borrowed here
   | 
  ::: /home/strohel/.cargo/git/checkouts/paperclip-bb3ea4fb155f1f50/90038bf/macros/src/lib.rs:39:1
   |
39 | #[proc_macro_error]
   | ------------------- in this expansion of `#[api_v2_operation]`
   |
note: closure is returned here
  --> src/handlers/city.rs:47:1
   |
47 | #[api_v2_operation]
   | ^^^^^^^^^^^^^^^^^^^ in this macro invocation
   | 
  ::: /home/strohel/.cargo/git/checkouts/paperclip-bb3ea4fb155f1f50/90038bf/macros/src/lib.rs:39:1
   |
39 | #[proc_macro_error]
   | ------------------- in this expansion of `#[api_v2_operation]`
help: to force the closure to take ownership of `app` (and any other referenced variables), use the `move` keyword
   |
47 | move #[api_v2_operation]
   |
```

User code with expanded macros:
```rust
        struct paperclip_get;
        #[doc =
          " The `/city/v1/get` endpoint. HTTP request: [`CityQuery`], response: [`CityResponse`]."]
        #[doc = ""]
        #[doc = " Get city of given ID localized to given language."]
        pub(crate) fn get(query: Query<CityQuery>, app: Data<AppState>)
         ->
             impl std::future::Future<Output = JsonResult<CityResponse>> +
             paperclip::v2::schema::Apiv2Operation {
            let f =
                (||
                     async 
                         {
                             let locations_es_repo =
                                 LocationsElasticRepository(app.get_ref());
                             let es_city =
                                 locations_es_repo.get_city(query.id).await?;
                             Ok(Json(es_city.into_resp(app.get_ref(),
                                                       query.language).await?))
                         })();
            paperclip::actix::ResponseWrapper{0: f, 1: paperclip_get,}
        }
```
<details>

```rust
        impl paperclip::v2::schema::Apiv2Operation for paperclip_get {
            fn operation() -> paperclip::v2::models::DefaultOperationRaw {
                use paperclip::actix::OperationModifier;
                let mut op =
                    paperclip::v2::models::DefaultOperationRaw::default();
                op.summary =
                    Some("The `/city/v1/get` endpoint. HTTP request: [`CityQuery`], response: [`CityResponse`].".to_string());
                op.description =
                    Some("Get city of given ID localized to given language.".to_string());
                <Query<CityQuery>>::update_parameter(&mut op);
                <Query<CityQuery>>::update_security(&mut op);
                <Data<AppState>>::update_parameter(&mut op);
                <Data<AppState>>::update_security(&mut op);
                <<paperclip::actix::ResponseWrapper<Box<dyn std::future::Future<Output
                                                                                =
                                                                                JsonResult<CityResponse>> +
                                                        std::marker::Unpin>,
                                                    paperclip_get> as
                 std::future::Future>::Output>::update_response(&mut op);
                op
            }
            #[allow(unused_mut)]
            fn security_definitions()
             ->
                 std::collections::BTreeMap<String,
                                            paperclip::v2::models::SecurityScheme> {
                use paperclip::actix::OperationModifier;
                let mut map = Default::default();
                <Query<CityQuery>>::update_security_definitions(&mut map);
                <Data<AppState>>::update_security_definitions(&mut map);
                map
            }
            fn definitions()
             ->
                 std::collections::BTreeMap<String,
                                            paperclip::v2::models::DefaultSchemaRaw> {
                use paperclip::actix::OperationModifier;
                let mut map = std::collections::BTreeMap::new();
                <Query<CityQuery>>::update_definitions(&mut map);
                <Data<AppState>>::update_definitions(&mut map);
                <<paperclip::actix::ResponseWrapper<Box<dyn std::future::Future<Output
                                                                                =
                                                                                JsonResult<CityResponse>> +
                                                        std::marker::Unpin>,
                                                    paperclip_get> as
                 std::future::Future>::Output>::update_definitions(&mut map);
                map
            }
        }
```
</details>

This might have been caused by 48429d12dce550fa89998c1b169112f01dad4d65 or 49a44282719b9376e0366e18b6cbd6057a21b9dc. CC @wafflespeanut @dunnock.

**Comment by wafflespeanut** [comment]
Yeah, this is my bad. It should be a `move` closure. :sweat_smile:
